#!/bin/bash -e

set -v

if [ ! -d ".venv" ]; then
	python3 -m venv ./.venv
fi

source ./.venv/bin/activate

mkdir -p ~/.cache/hoshino
if [ ! -e "~/.cache/hoshino/git.date" ]; then
	echo 0 > ~/.cache/hoshino/git.date
fi

now=$(date +%Y%m%d)

pip config set global.index-url https://mirrors.aliyun.com/pypi/simple/

if [ ! "$(cat ~/.cache/hoshino/git.date)" == "$now" ]; then
	timeout 1m git pull
	pip install nonebot wheel
	pip install -r requirements.txt
	find hoshino/modules -type f -name "requirements.txt" -print0 | xargs -0 -I {} sh -c 'if [ -f "{}" ]; then pip install -r "{}"; fi'
	echo "$now" > ~/.cache/hoshino/git.date
fi

python3 hoshino/modules/autopcr/download_web.py
python3 run.py
